INSERT INTO users VALUES (1, 'mat', 'test_hash_value', 'ADMIN');
INSERT INTO machines VALUES (1, 'harvester_mk1', 1, 0, 0, 1, 0, 1, TRUE);
INSERT INTO machines VALUES (2, 'smelter_mk1', 1, 1, 0, 1, 0, 1, TRUE);
INSERT INTO machines VALUES (3, 'constructor_mk1', 1, 1, 0, 1, 0, 1, TRUE);
INSERT INTO machines VALUES (4, 'assembler_mk1', 1, 2, 0, 1, 0, 1, TRUE);
INSERT INTO resources VALUES (1, 'iron_ore', 1, FALSE, '');
INSERT INTO resources VALUES (2, 'iron_ingot', 1, FALSE, '');
INSERT INTO resources VALUES (3, 'iron_plate', 1, FALSE, '');
INSERT INTO resources VALUES (4, 'iron_rod', 1, FALSE, '');
INSERT INTO resources VALUES (5, 'screw', 1, FALSE, '');
INSERT INTO resources VALUES (6, 'reinforced_iron_plate', 1, FALSE, '');
INSERT INTO recipies VALUES (1, 'iron_ore_harvesting_default', 1, 60, 'seconds', TRUE);
INSERT INTO recipies VALUES (2, 'iron_ingot', 1, 60, 'seconds', TRUE);
INSERT INTO recipies VALUES (3, 'iron_plate', 1, 60, 'seconds', TRUE);
INSERT INTO recipies VALUES (4, 'iron_rods', 1, 60, 'seconds', TRUE);
INSERT INTO recipies VALUES (5, 'screw', 1, 60, 'seconds', TRUE);
INSERT INTO recipies VALUES (6, 'reinforced_iron_plate', 1, 60, 'seconds', TRUE);
INSERT INTO recipies_inputs VALUES (1, 1, 2, 1, 30);
INSERT INTO recipies_inputs VALUES (2, 1, 3, 2, 30);
INSERT INTO recipies_inputs VALUES (3, 1, 4, 2, 15);
INSERT INTO recipies_inputs VALUES (4, 1, 5, 4, 10);
INSERT INTO recipies_inputs VALUES (5, 1, 6, 3, 30);
INSERT INTO recipies_inputs VALUES (6, 1, 6, 5, 60);
INSERT INTO recipies_outputs VALUES (1, 1, 1, 1, 60);
INSERT INTO recipies_outputs VALUES (2, 1, 2, 2, 30);
INSERT INTO recipies_outputs VALUES (3, 1, 3, 3, 20);
INSERT INTO recipies_outputs VALUES (4, 1, 4, 4, 15);
INSERT INTO recipies_outputs VALUES (5, 1, 5, 5, 40);
INSERT INTO recipies_outputs VALUES (6, 1, 6, 6, 5);
INSERT INTO machines_recipies VALUES (1, 1, 1, 1);
INSERT INTO machines_recipies VALUES (2, 1, 2, 2);
INSERT INTO machines_recipies VALUES (3, 1, 3, 3);
INSERT INTO machines_recipies VALUES (4, 1, 4, 3);
INSERT INTO machines_recipies VALUES (5, 1, 5, 3);
INSERT INTO machines_recipies VALUES (6, 1, 6, 4);